In [3]:
import numpy as np

In [6]:
arr = np.arange(25)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
ranarr = np.random.randint(0,50, 10)

In [12]:
ranarr

array([31,  3, 31, 31, 31, 45, 16, 30, 15, 16])

In [13]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr.shape

(25,)